Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('AP','Andhra Pradesh');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('AS','Assam ');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('BR','Bihar');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('CH','Chennai');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('DL','Delhi (includes NCR).');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('GJ','Gujarat');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('HP','Himachal Pradesh ');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('HR','Haryana');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('JK','Jammu and Kashmir');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('KL','Kerala');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('KA','Karnataka');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('KO','Kolkata');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('MH','Maharashtra ');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('MP','Madhya Pradesh');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('MU','Mumbai');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('NE','North East');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('OR','Odisha');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('PB','Punjab');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('RJ','Rajasthan');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('TN','Tamil Nadu');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('UE','Uttar Pradesh (East) ');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('UW','Uttar Pradesh (West)');
Insert into NetworkCircle (OpertorCircleCode,OpertorCircleDescription) values 	('WB','West Bengal');
