//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpportunityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network
    {
        public Network()
        {
            this.NetworkPlans = new HashSet<NetworkPlan>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NetworkCircleID { get; set; }
        public string Name { get; set; }
    
        public virtual NetworkCircle NetworkCircle { get; set; }
        public virtual ICollection<NetworkPlan> NetworkPlans { get; set; }
    }
}
