//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpportunityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOpsEntities : DbContext
    {
        public dbOpsEntities()
            : base("name=dbOpsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JoloAPICode> JoloAPICodes { get; set; }
        public virtual DbSet<Network> Networks { get; set; }
        public virtual DbSet<NetworkCircle> NetworkCircles { get; set; }
        public virtual DbSet<NetworkPlan> NetworkPlans { get; set; }
        public virtual DbSet<NumberNetworkCircle> NumberNetworkCircles { get; set; }
        public virtual DbSet<NumberType> NumberTypes { get; set; }
        public virtual DbSet<TransactionStatu> TransactionStatus { get; set; }
        public virtual DbSet<UserNumber> UserNumbers { get; set; }
        public virtual DbSet<UserPassword> UserPasswords { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<UserTransaction> UserTransactions { get; set; }
    }
}
