//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpportunityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> NetworkPlanID { get; set; }
        public int TransactionStatusID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    
        public virtual TransactionStatu TransactionStatu { get; set; }
    }
}
